pipeline {
agent any
environment {
ECR_REPO = '123456789012.dkr.ecr.us-east-1.amazonaws.com/${PROJECT_NAME}'
AWS_REGION = 'us-east-1'
}
stages {
stage('Checkout') {
steps { checkout scm }
}
stage('SonarQube') {
steps {
withSonarQubeEnv('SonarQube') {
sh 'mvn sonar:sonar -DskipTests'
}
}
}
stage('Quality Gate') {
steps {
waitForQualityGate(abortPipeline: true)
}
}
stage('Build Image') {
steps {
sh 'docker build -t ${ECR_REPO}:${GIT_COMMIT} .'
sh 'trivy image --exit-code 1 ${ECR_REPO}:${GIT_COMMIT} || true'
}
}
stage('Push to ECR') {
steps {
sh '''
aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REPO%%/*}
docker tag ${ECR_REPO}:${GIT_COMMIT} ${ECR_REPO}:latest
docker push ${ECR_REPO}:${GIT_COMMIT}
docker push ${ECR_REPO}:latest
'''
}
}
stage('Deploy to Kubernetes') {
steps {
sh 'helm upgrade --install myapp helm-chart --set image.repository=${ECR_REPO},image.tag=${GIT_COMMIT}'
}
}
}
}
